version: '2'

services:
  postgres:
    image: 'postgres:10.1-alpine'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  chermondis:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "api.app:create_app()"
    env_file:
      - '.env'
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/api'
    ports:
      - '8000:8000'

volumes:
  postgres:
